-- Auto-generated from schema-map-postgres.yaml (map@4ae85c5)
-- engine: postgres
-- table:  rbac_roles

CREATE TABLE IF NOT EXISTS rbac_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repo_id BIGINT NULL,
  slug VARCHAR(120) NOT NULL,                      -- stable role identifier
  name VARCHAR(200) NOT NULL,
  description TEXT NULL,
  version INTEGER NOT NULL DEFAULT 1,
  status  TEXT NOT NULL DEFAULT 'active',          -- 'active','deprecated','archived'
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT uq_rbac_roles_repo_slug UNIQUE (repo_id, slug),
  CONSTRAINT chk_rbac_roles_status CHECK (status IN ('active','deprecated','archived'))
);
